name: cf  

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 21 * * 5"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "appleatiger@gmail.com"
          git config --local user.name "appleatiger"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          date +"%Y-%m-%d %H:%M:%S.%N" > keepchange.txt
          git commit -am "cf"
          git push
